In [5]:
!conda install pytorch torchvision torchaudio -c pytorch-nightly -y

Channels:
 - pytorch-nightly
 - defaults
Platform: osx-arm64
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3

  added / updated specs:
    - pytorch
    - torchaudio
    - torchvision


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libjpeg-turbo-2.0.0        |       h1a28f6b_0         386 KB
    libwebp-1.3.2              |       ha3663a8_0          86 KB
    pytorch-2.6.0.dev20241112  |         py3.12_0        60.0 MB  pytorch-nightly
    torchaudio-2.5.0.dev20241118|        py312_cpu         4.9 MB  pytorch-nightly
    torchvision-0.20.0.dev20241118|        py312_cpu         7.0 MB  pytorch-nightly
    ------------------------------------------------------------
                                           Total:        72.4 MB

The following NEW packages will be INSTALLED:

  libjpeg-turbo      pkgs/main/osx-arm64::libjpeg-turbo-2.0.0-h1a28f6b_0 


In [100]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0.dev20241112


In [102]:
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

tensor([1.], device='mps:0')


## Scalar | Vector | Tensor

In [105]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [107]:
scalar.ndim

0

In [109]:
scalar.item()

7

In [111]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [113]:
vector.ndim

1

In [115]:
vector.shape

torch.Size([2])

In [117]:
#Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [119]:
MATRIX.ndim

2

In [121]:
MATRIX[1]

tensor([ 9, 10])

In [123]:
MATRIX.shape

torch.Size([2, 2])

In [125]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6], [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [127]:
TENSOR.ndim

3

In [129]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors

In [132]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4858, 0.3719, 0.0682, 0.9626],
        [0.7471, 0.4460, 0.6698, 0.7832],
        [0.8879, 0.5181, 0.8355, 0.8131]])

In [134]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [136]:
# Zeros and Ones
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [138]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [140]:
ones.dtype

torch.float32

In [142]:
torch.arange(start=1,end=1000,step=50)

tensor([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451, 501, 551, 601, 651,
        701, 751, 801, 851, 901, 951])

In [144]:
float_32_tensor = torch.tensor([3,6,9], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3, 6, 9])

In [146]:
float_32_tensor.dtype

torch.int64

In [148]:
float_32_tensor*float_32_tensor

tensor([ 9, 36, 81])

In [150]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0598, 0.6549, 0.4641, 0.9751],
        [0.0907, 0.2251, 0.8202, 0.7866],
        [0.7911, 0.8690, 0.7372, 0.2456]])

In [152]:
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.size()}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.0598, 0.6549, 0.4641, 0.9751],
        [0.0907, 0.2251, 0.8202, 0.7866],
        [0.7911, 0.8690, 0.7372, 0.2456]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device tensor is on : cpu


## Manipulation Tensor

In [155]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [157]:
tensor * 10

tensor([10, 20, 30])

In [159]:
tensor - 1

tensor([0, 1, 2])

In [161]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [163]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

In [166]:
# Element wise
tensor * tensor

tensor([1, 4, 9])

In [168]:
torch.matmul(tensor,tensor)

tensor(14)

In [170]:
ele1 = torch.rand(3,3)
ele2 = torch.rand(3,3)
ele1, ele2

(tensor([[0.9935, 0.4165, 0.4931],
         [0.4315, 0.6676, 0.4714],
         [0.5812, 0.3488, 0.8976]]),
 tensor([[0.9681, 0.7927, 0.3685],
         [0.2325, 0.5181, 0.5588],
         [0.0056, 0.9610, 0.5128]]))

In [172]:
torch.matmul(ele1,ele2)

tensor([[1.0615, 1.4772, 0.8516],
        [0.5756, 1.1410, 0.7737],
        [0.6488, 1.5040, 0.8693]])

In [179]:
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)


In [181]:
torch.matmul(tensor,tensor)

tensor(14)

In [183]:
tensor @ tensor

tensor(14)