In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

Matplotlib is building the font cache; this may take a moment.


2.6.0.dev20241112


In [8]:
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

tensor([1.], device='mps:0')


## Scalar | Vector | Tensor

In [12]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [14]:
scalar.ndim

0

In [16]:
scalar.item()

7

In [19]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [21]:
vector.ndim

1

In [23]:
vector.shape

torch.Size([2])

In [27]:
#Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [29]:
MATRIX.ndim

2

In [31]:
MATRIX[1]

tensor([ 9, 10])

In [33]:
MATRIX.shape

torch.Size([2, 2])

In [35]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6], [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [37]:
TENSOR.ndim

3

In [41]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors

In [46]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5411, 0.7134, 0.7280, 0.0593],
        [0.8736, 0.4819, 0.7786, 0.0123],
        [0.1313, 0.1161, 0.4622, 0.6609]])

In [50]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [52]:
# Zeros and Ones
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [56]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [58]:
ones.dtype

torch.float32

In [70]:
torch.arange(start=1,end=1000,step=50)

tensor([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451, 501, 551, 601, 651,
        701, 751, 801, 851, 901, 951])